Bandango.Compra = DS.Model.extend Bandango.OrderItemsMixin,
  fechaRegistro:                       DS.attr()
  numeroSerieEstablecimiento:          DS.attr()
  numeroSeriePuntoEmision:             DS.attr()
  numeroSerieComprobante:              DS.attr()
  fechaEmision:                        DS.attr()
  autorizacionComprobante:             DS.attr()
  retencionIvaBienes:                  DS.attr()
  retencionIvaServicios:               DS.attr()
  retencionIvaCien:                    DS.attr()
  baseImponibleRenta:                  DS.attr()
  porcentajeRetencionFuente:           DS.attr()
  numeroSerieRetencionEstablecimiento: DS.attr()
  numeroSerieRetencionPuntoEmision:    DS.attr()
  numeroSerieRetencion:                DS.attr()
  numeroAutorizacionRetencion:         DS.attr()
  fechaEmisionRetencion:               DS.attr()
  formaDePago:                         DS.attr()

  sustentoComprobante:                 DS.belongsTo("sustentoComprobante")
  comprobante:                         DS.belongsTo("comprobante")
  retenciones:                         DS.hasMany("retencion")
  orderItems:                          DS.hasMany("orderItem")
  cliente:                             DS.belongsTo("cliente")
