Bandango.Emisor = DS.Model.extend
  ruc:                                   DS.attr()
  razonSocial:                           DS.attr()
  nombreComercial:                       DS.attr()
  direccionMatriz:                       DS.attr()
  direccionEstablecimiento:              DS.attr()
  autorizacionComprobantes:              DS.attr()
  codigoEstablecimiento:                 DS.attr()
  codigoPuntoEmision:                    DS.attr()
  contribuyenteEspecialNumeroResolucion: DS.attr()
  obligadoLlevarContabilidad:            DS.attr()
  imagenUrl:                             DS.attr()
