# encoding: utf-8
comprobantes = [
  { codigo: 1,
    tipo: "Factura",
    codigo_secuenciales: [1, 9],
    sustento_tributario: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0] },
  { codigo: 2,
    tipo: "Nota o boleta de venta",
    codigo_secuenciales: [1],
    sustento_tributario: [2, 4, 5, 7, 8, 9, 0] },
  { codigo: 3,
    tipo: "Liquidación de compra de Bienes o Prestación de servicios",
    codigo_secuenciales: [2, 3],
    sustento_tributario: [1, 2, 3, 4, 5, 6, 7, 8] },
  { codigo: 4,
    tipo: "Nota de crédito",
    codigo_secuenciales: [1, 2, 3, 4, 5, 6, 7, 9],
    sustento_tributario: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0] },
  { codigo: 5,
    tipo: "Nota de débito",
    codigo_secuenciales: [1, 2, 3, 4, 5, 6, 7, 9],
    sustento_tributario: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0] },
  { codigo: 7,
    tipo: "Comprobante de Retención" },
  { codigo: 8,
    tipo: "Boletos o entradas a espectáculos públicos",
    codigo_secuenciales: [1] },
  { codigo: 9,
    tipo: "Tiquetes o vales emitidos por máquinas registradoras",
    codigo_secuenciales: [1] },
  { codigo: 11,
    tipo: "Pasajes expedidos por empresas de aviación",
    codigo_secuenciales: [1],
    sustento_tributario: [1, 2, 5] },
  { codigo: 12,
    tipo: "Documentos emitidos por instituciones financieras",
    codigo_secuenciales: [1],
    sustento_tributario: [1, 2, 5] },
  { codigo: 15,
    tipo: "Comprobante de venta emitido en el Exterior",
    codigo_secuenciales: [3],
    sustento_tributario: [2, 4, 5, 7] },
  { codigo: 16,
    tipo: "Formulario Único de Exportación (FUE) o Declaración Aduanera Única (DAU) o Declaración Andina de Valor (DAV)",
    codigo_secuenciales: [9] },
  { codigo: 18,
    tipo: "Documentos autorizados utilizados en ventas excepto N/C N/D ",
    codigo_secuenciales: [4, 5, 6, 7] },
  { codigo: 19,
    tipo: "Comprobantes de Pago de Cuotas o Aportes",
    codigo_secuenciales: [1, 2],
    sustento_tributario: [2] },
  { codigo: 20,
    tipo: "Documentos por Servicios Administrativos emitidos por Inst. del Estado",
    codigo_secuenciales: [1],
    sustento_tributario: [2] },
  { codigo: 21,
    tipo: "Carta de Porte Aéreo",
    codigo_secuenciales: [1],
    sustento_tributario: [1, 2, 8] },
  { codigo: 22,
    tipo: "RECAP",
    codigo_secuenciales: [10, 11] },
  { codigo: 23,
    tipo: "Nota de Crédito TC",
    codigo_secuenciales: [10, 11] },
  { codigo: 24,
    tipo: "Nota de Débito TC",
    codigo_secuenciales: [10, 11] },
  { codigo: 41,
    tipo: "Comprobante de venta emitido por reembolso",
    codigo_secuenciales: [1, 4, 5, 6, 9],
    sustento_tributario: [1, 2, 3, 4, 5, 6, 7] },
  { codigo: 42,
    tipo: "Documento agente de retención Presuntiva",
    codigo_secuenciales: [1],
    sustento_tributario: [0] },
  { codigo: 43,
    tipo: "Liquidacion para Explotacion y Exploracion de Hidrocarburos",
    codigo_secuenciales: [1],
    sustento_tributario: [1, 2, 6, 7] },
  { codigo: 44,
    tipo: "Comprobante de Contribuciones y Aportes",
    codigo_secuenciales: [4, 5, 6] },
  { codigo: 45,
    tipo: "Liquidación por reclamos de aseguradoras",
    codigo_secuenciales: [1, 3],
    sustento_tributario: [9] },
  { codigo: 47,
    tipo: "Nota de Crédito por Reembolso Emitida por Intermediario",
    codigo_secuenciales: [1, 4, 5, 6, 9],
    sustento_tributario: [1, 2, 3, 4, 6, 7] },
  { codigo: 48,
    tipo: "Nota de Débito por Reembolso Emitida por Intermediario",
    codigo_secuenciales: [1, 4, 5, 6, 9],
    sustento_tributario: [1, 2, 3, 4, 6, 7] },
  { codigo: 49,
    tipo: "Proveedor Directo de Exportador Bajo Régimen Especial",
    codigo_secuenciales: [4] },
  { codigo: 50,
    tipo: "A Inst. Estado y Empr. Públicas que percibe ingreso exento de Imp. Renta",
    codigo_secuenciales: [4] },
  { codigo: 51,
    tipo: "N/C A Inst. Estado y Empr. Públicas que percibe ingreso exento de Imp. Renta",
    codigo_secuenciales: [4] },
  { codigo: 52,
    tipo: "N/D A Inst. Estado y Empr. Públicas que percibe ingreso exento de Imp. Renta",
    codigo_secuenciales: [4] }
].each do |comprobante|
  Comprobante.where(codigo: comprobante[:codigo]).first_or_initialize.tap do |c|
    c.update_attributes! comprobante
  end
end
